# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='active',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
